import type { LucideIcon } from "lucide-react";
import {
  Beef,
  Soup,
  Pizza,
  Donut,
  Apple,
  GlassWater,
  Utensils,
  Container,
  Flame,
  LayoutGrid,
  Fish,
  Milk,
  ShoppingBag,
  Gem,
  Cpu,
  Hammer,
  Grape,
} from "lucide-react";

export const CATEGORY_ICON_MAP: Record<string, LucideIcon> = {
  sets: LayoutGrid,
  rolls: Utensils,
  sushi: Beef,
  shaurma: Beef,
  wok: Flame,
  soups: Soup,
  snacks: Pizza,
  desserts: Donut,
  drinks: GlassWater,
  ikra: Fish,
  boroshno: Grape,
  kosmetika: Gem,
  "makaronni-vyroby": Soup,
  "nozhi-kukhonni": Hammer,
  "ovocheva-konservatsiya": Apple,
  "odnorazovyy-posud": Container,
  "panirovalni-sukhari": Flame,
  "podarunkovi-paketi": ShoppingBag,
  "posud-dlya-sushi": Container,
  "produkti-dlya-sushi": Utensils,
  "ryba-ta-moreprodukty": Fish,
  "roslynne-moloko": Milk,
  syry: Milk,
  sousy: GlassWater,
  "spetsiyi-ta-prypravy": Flame,
  "susheni-ovochi": Apple,
  tekhnika: Cpu,
};
